name: Git tags

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:



jobs:
  build:
    runs-on: ubuntu-latest
    name: Build
    steps:
      - uses: actions/checkout@v6

      - name: show git tags
        run: |
          git tags
